### ISSUE TITLE
Add -p --packonly parameter

### ISSUE THREAD

**Issue by pixlcrashr** [KoffeinFlummi/armake2#6]
A parameter such as the same of `armake` should exist in `armake2`.

`-p` as the short form for pack only.
`--packonly` as the parameter name.

The implementation shouldn't be a problem.

**Comment by Krzmbrzl** [comment]
According to the Readme there now is a `pack` command that replaces the need for a `build -p`

**Comment by pixlcrashr** [comment]
That is certainly correct, but there is no way to define custom prefixes with the `armake2 pack` command. Since `armake2 build` has nearly the same functionality as `armake2 pack`, it would be more clever to combine both commands as it was done in `armake`.

**Comment by jonpas** [comment]
I support this, `build -p` makes a lot more sense. Equally easily accessible with less arguments clutter both for user and in code.

**Comment by Krzmbrzl** [comment]
I think we maybe could remove the pack-command internally and simply make it an alias for `build -p`. That way `pack` has all the customizability of `build` and everyone who doesn't like to type `build -p` dient have to...

**Comment by pixlcrashr** [comment]
And what is about the usage of other parameters given by `build`? Should there be any way to use e.g. prefixes on `build -p` builds?

I guess, that just creating an alias is not enough to support other `build`-features.

**Comment by Krzmbrzl** [comment]
Using the alias would enable you to use every single available option that exists for the `build` command. The only difference would be that files would not be rapified nor preprocessed.

**Comment by pixlcrashr** [comment]
... That is exactly what I meant. I was a bit confused by your text as you say that `build -p` should be an _alias_ to `pack`. Probably you meant that parameter `-p` should implement the functionality for disabling binarization. As it would be clearer to understand, technically.
Nevermind.

**Comment by Krzmbrzl** [comment]
I was saying that we should make `pack` an alias for `build -p`. So that typing `pack` will be treated as if one had typed `build -p`.
That would - as a precondition - mean that we'd have to bring back the `-p` switch in the first place though.

The whole alias thingy is just in order to not throw out KoeffeinFlummi's effort to provide an easier way for people to achieve no-binarization and in order to comply with the current usage-specification.

**Comment by KoffeinFlummi** [comment]
The reason I introduced the seperation in the first place was to make the command invocation more explicit (instead of defining an action, and then restricting that action via an option, you just define a different action) and so that the usage string makes it clear which arguments are available for which action.

With a `-p` option, one argument can invalidate another argument (the include folder argument is useless if you also add `-p`), which is a bit ugly in my opinion.

The only missing option for packing was the header extension one, which I added: c18bd7ec546f9475ee34290dcf4d657599a69171. The warnings option is not needed, as the pack command currently never emits any named warnings.
